# Generated by Django 4.0.4 on 2022-05-16 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('nom', models.CharField(default='equipement0', max_length=200)),
                ('etat', models.CharField(choices=[('fontionnel', 'foncionnel'), ('en panne', 'en panne')], default='fontionnel', max_length=200)),
                ('dateentrer', models.DateTimeField(auto_now_add=True, null=True)),
                ('datemodif', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categorie.categorie')),
            ],
        ),
    ]
