# Generated by Django 4.0.4 on 2022-05-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='destinataire',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='message',
            name='expediteur',
            field=models.CharField(default=' Anonymous ', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(default=' ', max_length=2400, null=True),
        ),
    ]
