# Generated by Django 4.0.4 on 2022-05-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorie', '0002_remove_categorie_id_alter_categorie_nomc'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorie',
            name='nomc',
            field=models.CharField(max_length=200),
        ),
    ]
