# Generated by Django 4.0.4 on 2022-05-16 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panne', '0001_initial'),
        ('equipement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etatp', models.CharField(choices=[('Non Resolu', 'Non Resolu'), ('Resolu', 'Resolu')], default='Non Resolu', max_length=200)),
                ('datesg', models.DateField(auto_now_add=True, null=True)),
                ('equipement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipement.equipement')),
                ('panne', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panne.panne')),
            ],
        ),
    ]
