# Generated by Django 4.0.4 on 2022-05-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Panne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codep', models.CharField(max_length=20)),
                ('nomp', models.CharField(max_length=200)),
                ('priorite', models.IntegerField(default=1, null=True)),
            ],
        ),
    ]
